### ISSUE TITLE
sLockscreenctl - args for i3lock-color changed

### ISSUE THREAD

**Issue by ghost** [simonvic/dotfiles#10]
Hi,

Seems that args have changed.
I can list it up for you

Do you have the same issue ?

By advance, thank you

**Comment by simonvic** [comment]
hey :)

mmh... nope
I'm currently on i3lock-color 2.13.c.4-1, which seems to be the last release on the github repo (https://github.com/Raymo111/i3lock-color/releases)

Are you using some forked version?

**Comment by ghost** [comment]
Hello :)

Yes I'm using the same version as you.

This is what I get when I launch manually: 

> sLockscreenctl l
> No players found
> No players found
> No players found
> %A, %d %B
> i3lock: unrecognized option '--indpos=960:785'
> i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-f]
> Please see the manpage for a full list of arguments.
>

**Comment by simonvic** [comment]
oops my bad 😅 
I forgot to update the arguments when using the `bars` indicator type

it has been fixed in the dev branch [ 8631ea575061deb56953bfa92a29a21d432fa3c6 ]

thanks for the report :)

**Comment by ghost** [comment]
Yep, I confirm it's working, do you need help here ?
