### ISSUE TITLE
Missing fonts ?

### ISSUE THREAD

**Issue by ghost** [simonvic/dotfiles#7]
Hi !

First of all, thank you for sharing your dotfiles.
You do an amazing work and well documented.

I am having an issue while installing your dotfiles, Polybar don't load correctly, my guess is that I'm having a missing font issue.
For example, I can't see the glyph [here](https://github.com/simonvic/dotfiles/blob/6529fb016d05484bfa796d661d9270dd6f765350/.config/polybar/config#L220) (from Firefox or after downloaded it)

I've installed every fonts you recommend except ttf-material-wifi-icons-git

By advance, thank you.

**Comment by ghost** [comment]
Hi,

I still have a font issue, but my main problem is resolved.
I didn't understand why main bar wasn't loading, just because of a module.

**Comment by simonvic** [comment]
hey, thanks!

I can't see it from Firefox neither, but as long you've installed the right font it should be fine.
The `u+f073` is inside the NerdFonts iosevka.
https://github.com/simonvic/dotfiles/wiki/Installation-and-Configuration#gtk-theme-icons-theme-and-fonts

Try to update the font cache
```
fc-cache
```

**Comment by ghost** [comment]
Hi !

Thank you for your answer and I actually did that command, restart X, now everything is working.

Thank you :)
