### ISSUE TITLE
sLockscreenctl unrecognized option

### ISSUE THREAD

**Issue by Elsie19** [simonvic/dotfiles#8]
Output
```bash
henry@twilight ~ % ››› .local/bin/sLockscreenctl lock
%A, %d %B
i3lock: unrecognized option '--indpos=960:785'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-f]
Please see the manpage for a full list of arguments.
henry@twilight ~ % ›››
```

i3lock: version 2.13.c.3 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li

**Comment by simonvic** [comment]
@Henryws what version of i3lock are you using? Have you installed the i3lock-color fork from [here](https://aur.archlinux.org/packages/i3lock-color/)?

**Comment by Elsie19** [comment]
Yeah, i3lock-color, and the version is above (2.13.c.3)

**Comment by simonvic** [comment]
hey sorry, I was still using the 2.13.c.2
In 2.13.c.3 all options have been renamed, I'll update sLockscreenctl to be compatible with the new version as soon as possible

**Comment by Elsie19** [comment]
thank you

**Comment by simonvic** [comment]
thanks for the report!
The fix is live :)
